application: example
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: latest

builtins:
- remote_api: on

handlers:
- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)
  login: required
  secure: always

- url: /bower_components/(.*)/(.*\.(html|css|js|js.map))
  static_files: bower_components/\1/\2
  upload: bower_components/(.*)/(.*\.(html|css|js|js.map))
  login: required
  secure: always

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  login: required
  secure: always

- url: /report/.*
  script: report.application
  # Login is intentionally not required here, but there are
  # user authorization handled by auth.py.
  secure: always

- url: /search/
  script: search.application
  # login authentication handled per group by auth.py check.
  login: required
  secure: always

- url: /settings/
  script: settings.application
  # login authentication handled per group by auth.py check.
  login: required
  secure: always

- url: /update/.*
  script: datastore.application
  login: admin
  secure: always

- url: /.*
  script: admin.application
  # login authentication handled per group by auth.py check.
  login: required
  secure: always
